[build-system]
<<<<<<< HEAD
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "isprime-kaatre"
version = "0.1.0"
description = "A simple package to check for prime numbers"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
  { name = "Manish Rakaskoti", email = "newfeed4554@gmail.com" }
]
dependencies = []

[project.urls]
Homepage = "https://github.com/kaatreHx/isprime"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
=======
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "is-prime-checker"
version = "0.1.0"
description = "A simple package to check if a number is prime"
readme = "README.md"
authors = [{ name = "Manish Rakaskoti", email = "newsfeed4554@gmail.com" }]
license = {text = "MIT"}
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["src/is_prime_checker"]
>>>>>>> a58969f3ee3642b9746200b67d8da086c316e748
